TRAINING:
    PRINT_FREQ: 50
    EPOCHS: 70
    BATCH_SIZE:
        BS_TRAIN: 128
        BS_TEST: 256
    LOSS:
        NAME: CROSS ENTROPY
        BETA: 1
    KD:
        TEMPERATURE: 4
        DELTA: 0
    OPTIMIZER:
        NAME: SGD
        LR: 0.1
        LR_DECAY: 25
        GAMMA: 0.1
    SCHEDULER:
        NAME: STEP # Possibilities: STEP, WARM-UP

VALIDATION:
    PRINT_FREQ: 50
    BATCH_SIZE:
        BS_TRAIN: 256
        BS_TEST: 256
    TEN_CROP: False