TRAINING:
    PRINT_FREQ: 100
    EPOCHS: 240
    BATCH_SIZE:
        BS_TRAIN: 128
        BS_TEST: 256
    LOSS:
        NAME: CROSS ENTROPY
        BETA: 1
    KD:
        TEMPERATURE: 4
        DELTA: 0
    OPTIMIZER:
        NAME: SGD
        LR: 0.05
        WEIGHT_DECAY: 5e-4
    SCHEDULER:
        NAME: MULTISTEP # Possibilities: STEP, MULTISTEP
        LR_DECAY: [150, 180, 210]
        GAMMA: 0.1

VALIDATION:
    PRINT_FREQ: 50
    BATCH_SIZE:
        BS_TRAIN: 256
        BS_TEST: 256
    TEN_CROP: False