MODEL:
    ARCH: ResNet56
    COMMENTS: Comment
    OUTPUT_DIR: Results
    PRETRAINED: None # Possibilities EPIC, Places or None
    FINETUNNING: False

    # Spatial HyperParameters
    RESIZE: 256
    CROP: 224
