MODEL:
    ARCH: ResNet50
    COMMENTS: Comment
    OUTPUT_DIR: Results
    PRETRAINED: ImageNet # Possibilities ImageNet or None
    FINETUNNING: False

    # Spatial HyperParameters
    RESIZE: 256
    CROP: 224
