MODEL:
    ARCH: ResNet18
    COMMENTS: Comment
    OUTPUT_DIR: Results
    PRETRAINED: None # Possibilities EPIC, ImageNet, Kinectics or None

    # Spatial HyperParameters
    RESIZE: 256
    CROP: 224
