DISTILLATION:
    TEACHER: 'Teacher ResNet50 ADE20K' # Options, Path or None
    D_LOSS: CRD
    ALPHA: 1.4 # Original (0.8)
    PERCENTAGE_CHANGE_ALPHA: 0
    MULTISCALE: True
    K: 16384
    T: 0.07
    M: 0.5
    FEAT_DIM: 128

